# Generated by Django 3.2 on 2021-07-09 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='bangunanpogung',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peta.pemilik'),
        ),
    ]
