# Generated by Django 3.2 on 2021-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0002_auto_20210709_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunanpogung',
            name='pemilik',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Pemilik',
        ),
    ]
